version: '3.8'

services:
  crypto-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: live-crypto-bot
    restart: always
    volumes:
      - ./appsettings.json:/app/appsettings.json
