version: '3.8'

services:
  crypto-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: live-crypto-bot
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TelegramBot__Token=YOUR_SECRET_TELEGRAM_BOT_TOKEN
